services:
  - type: web
    name: enemeop-evolution
    runtime: image
    image:
      url: docker.io/atendai/evolution-api:latest
    plan: free
    region: oregon
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: SERVER_TYPE
        value: http
      - key: AUTHENTICATION_TYPE
        value: apikey
      - key: AUTHENTICATION_API_KEY
        value: enemeop_evo_key_2026
      - key: DATABASE_ENABLED
        value: "true"
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_CONNECTION_URI
        value: postgresql://postgres.gftnjvdvzgjkhwxnxnwl:Enemeop@Flores2026!@aws-0-sa-east-1.pooler.supabase.com:5432/postgres
      - key: DATABASE_SAVE_DATA_INSTANCE
        value: "true"
      - key: DATABASE_SAVE_DATA_NEW_MESSAGE
        value: "true"
      - key: DATABASE_SAVE_MESSAGE_UPDATE
        value: "true"
      - key: DATABASE_SAVE_DATA_CONTACTS
        value: "true"
      - key: DATABASE_SAVE_DATA_CHATS
        value: "true"
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        value: rediss://default:gQAAAAAAAjnhAAIgcDI0MWMxM2ZiMGZlYzE0NGFjOWI1ODhiZGQzNzViODVhZA@legal-imp-145889.upstash.io:6379
      - key: CACHE_REDIS_PREFIX_KEY
        value: evolution
      - key: DEL_INSTANCE
        value: "false"
      - key: LANGUAGE
        value: pt-BR
      - key: LOG_LEVEL
        value: ERROR
      - key: LOG_COLOR
        value: "false"
