services:
  - type: web
    name: enemeop-evolution
    runtime: image
    image:
      url: docker.io/atendai/evolution-api:latest
    plan: free
    region: oregon
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: AUTHENTICATION_TYPE
        value: apikey
      - key: AUTHENTICATION_API_KEY
        value: enemeop_evo_key_2026
      - key: DATABASE_ENABLED
        value: "true"
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_CONNECTION_URI
        value: postgresql://evolution_db_1wyh_user:NxBYm9crYPvUH8ohTfS8KOF3eyZ5B6UE@dpg-d8k78m6gvqtc73bi7190-a/evolution_db_1wyh
      - key: DATABASE_URL
        value: postgresql://evolution_db_1wyh_user:NxBYm9crYPvUH8ohTfS8KOF3eyZ5B6UE@dpg-d8k78m6gvqtc73bi7190-a/evolution_db_1wyh
      - key: DATABASE_SAVE_DATA_INSTANCE
        value: "true"
      - key: DATABASE_SAVE_DATA_NEW_MESSAGE
        value: "true"
      - key: CACHE_REDIS_ENABLED
        value: "false"
      - key: DEL_INSTANCE
        value: "false"
      - key: LANGUAGE
        value: pt-BR
      - key: LOG_LEVEL
        value: ERROR
